sonic-net/sonic-linkmgrd

- src/link_manager/LinkManagerStateMachine.cpp
- src/link_manager/LinkManagerStateMachine.h
- test/FakeMuxPort.h
- test/LinkManagerStateMachineTest.cpp
Summary:
Fix the issue that randomly fails MUX state toggling. 
To be more specific, the issue was when trying to toggle MUX ports from standby to active utilizing cli  "config mux mode standby all", some random ports won't be toggled successfully and will remain standby mode. This issue can be easily reproduced when ICMP_responder is off but not when the ports are in healthy state. 
The cause is when ICMP_responder is off and ToRs stay in unhealthy state, linkmgrd will probe mux state every 300ms[^1]  which will make mux state enter "wait". While mux state equals "wait", linkmgrd won't switch mux sate to user's desiring state[^2]. 
A state machine diagram for this particular scenario can be found under the internal sharepoint folder for Gemini design doc.  
[^1]: This …
> Fix MUX toggling issue 

- test/LinkManagerStateMachineTest.cpp
Summary:
Fixes # (issue) 
Fix unstable unit tests.
People observed that linkmgrd unit tests appeared to be flaky, and kept failing PR checks. After checking the build logs, I found that in most of the failures, the state change handler didn't seem to be invoked: Linkmgrd's composite state remained as it was before the state change was post. 
This PR updates code to invoke io_service::reset(), sets the io_service to no longer be in a stopped state, allowing subsequent calls to run_one() to invoke handlers. (When io_service is stopped, any call to run_one() will return immediately without invoking any handler. ) 
Signed-off-by: Jing Zhang <zhangjing@microsoft.com>
Stabilize linkmgrd unit tests. 
Reset stopped io_service before calling to run_one(), to guarantee state change handlers are …
> Fix unstable unit tests (state change handler wasn't invoked)

- test/LinkManagerStateMachineTest.cpp
Summary:
For those mux unknown states change tests, once the link manager state machine enters states like `(unknown, unknown, up/down)` or `(wait, unknown, up/down)`, after `mDeadlineTimer` timeouts, the state machine will enter intermediate states with mux state as `wait`.
Cover the state changes to those intermediate states:
* `(unknown, unknown, up/down)` ---> `(unknown, wait, up/down)`
* `(wait, unknown, up/down)` ---> `(wait, wait, up/down)`
> [unittest] Add missing intermediate states

- src/DbInterface.cpp
- src/DbInterface.h
- src/MuxManager.cpp
- src/MuxManager.h
- src/MuxPort.cpp
- src/MuxPort.h
- src/link_manager/LinkManagerStateMachine.cpp
- src/link_manager/LinkManagerStateMachine.h
- test/LinkManagerStateMachineTest.cpp
- test/LinkManagerStateMachineTest.h
Summary:
In the current Gemini linkmgrd design, when ICMP pinging consistently fails, a link prober unknown event won't trigger a switchover. In this scenario, if active side's cable is unplugged, there won't be a toggle to switch standby side to active. This PR is to handle this edge case.  
To make sure switchover happens when active side's cable is unplugged even when ICMP is not working. 
Make linkmgrd listen to MUX_CABLE_INFO table, which stores peer's link status. This peer's link status will be probed and updated through I2C from MUX every 60s. 
Added Unit tests. Also tested this change on dual testbed, toggling happened as expected.
> [linkmgrd] linkmgrd subscribes MUX_CABLE_INFO table to handle peer OIR events

- src/link_manager/LinkManagerStateMachine.cpp
- src/link_manager/LinkManagerStateMachine.h
- test/FakeMuxPort.cpp
- test/LinkManagerStateMachineTest.cpp
Summary:
XCVRD on a ToR can crash in different scenarios, and currently the expected behaviors are: 
1. Crashing when toggling to Active
1. Toggle triggered by ```sudo config mux standby``` on peer 
Expected to succeed. Peer will toggle mux. No action is needed. 
1. Toggle triggered by ```sudo config mux active```
Expected to fail. Nothing can be done to help.    
1. Toggle Triggered by LinkProber: Unknown
Expected to fail. Nothing can be done to help.  
1. Toggle Triggered by peer link status down (OIR)
Expected to fail. Nothing can be done to help.  
1. linkmgrd mismatching last updated xcvrd state
Can’t be sure if the last updated state is accurate, if Mux is: 
a. Pointing to local ToR
Expected to succeed. 
b. Pointing to peer ToR
Expected to fail. Local ToR ends in …
> Handle xcvrd crashing scenarios

- src/DbInterface.cpp
- src/link_manager/LinkManagerStateMachine.cpp
Summary:
Currently mux probing's log level is info (linkmgrd's default level is warning), this makes debugging harder, as to trigger mux state probing is a very important move of linkmgrd's state transition logic. 
We also don't have mux state change logging in warning level. 
To have important log in default logging level.
> Update log level for mux probing and mux state chance

- src/DbInterface.cpp
- src/DbInterface.h
- src/LinkMgrdMain.cpp
- src/MuxManager.h
- src/MuxPort.cpp
- src/MuxPort.h
- src/common/StateMachine.h
- src/link_manager/LinkManagerStateMachine.cpp
- src/link_manager/LinkManagerStateMachine.h
- src/link_manager/LinkManagerStateMachineBase.cpp
- src/link_manager/LinkManagerStateMachineBase.h
- src/link_manager/subdir.mk
- src/link_prober/LinkProberStateMachine.cpp
- src/link_prober/LinkProberStateMachine.h
- src/link_state/LinkStateMachine.cpp
- src/link_state/LinkStateMachine.h
- src/mux_state/MuxStateMachine.cpp
- src/mux_state/MuxStateMachine.h
- test/FakeDbInterface.cpp
- test/FakeDbInterface.h
- test/FakeMuxPort.cpp
- test/FakeMuxPort.h
- test/LinkManagerStateMachineTest.h
- test/MuxManagerTest.cpp
- test/MuxManagerTest.h
Summary:
Add abstract class `LinkManagerStateMachineBase` to represent common interfaces for link manager state machines that could be shared by both active/active state machine and active/standby state machine.
1. Rename `LinkManagerStateMachine` to `ActiveStandbyStateMachine`
2. Add abstract parent class `LinkManagerStateMachineBase`, which is derived from class `StateMachine`.
3. Let `ActiveStandbyStateMachine` be a child class of `LinkManagerStateMachineBase`
Build without error and all unit tests passed
> Add abstract class `LinkManagerStateMachineBase`

- src/link_manager/LinkManagerStateMachine.cpp
- src/link_manager/LinkManagerStateMachine.h
- test/MuxManagerTest.cpp
Summary:
This PR is to handle ```config mux mode standby/active``` failure on healthy ports caused by unexpected mismatching mux probe response.
What I firstly observed is a mux state probing right after a switchover can be mismatching with state db, and there was no additional switchover happened between the toggle and probe. Conducted an experiment and further proved that there is a time gap between xcvrd's toggle and the mux probe state change. 
This can trigger an undesirable switchback, and eventually appears to be a failure of ```config mux mode```. 
* Issue
For example, expected state change sequence of switching to active is: 
```
standby (Link Prober), standby (Local Mux State) 
-> wait, wait
-> wait, active (receive mux state notification, indicating toggle …
```
> Incrementing tolerance on mux state inconsistency 

- src/link_manager/LinkManagerStateMachine.cpp
- test/LinkManagerStateMachineTest.cpp
Summary:
This is to fix the issue that linkmgrd writes `unknown` to app db, or in other words, switches MUX to unknown, which can only be triggered by state db mismatching LinkManager mux state. 
```
~$ sudo show mux metrics Ethernet116 
PORT         EVENT                          TIME
-----------  -----------------------------  ---------------------------
Ethernet116  linkmgrd_switch_unknown_start  2022-Mar-07 23:56:48.865163
```
Switching to `unknown` doesn't make sense, and can cause confusion. 
Tested on virtual testbed.
> Prevent switching MUX to "Unknown"

- src/MuxManager.cpp
- src/MuxManager.h
- src/common/MuxPortConfig.h
Summary:
If a port is not in the `MUX_CABLE` table, `linkmgrd` still receives link up state, and calls `addOrUpdateMuxPortLinkState` to try to create a `MuxPort` object, in this case, the creation will fail due to the not-existed port cable type entry in the port cable type map.
Add a getter `getMuxPortCableType` to `MuxManager`, if the port cable type map doesn't have an entry, set it with the default port cable mode `active-standby`
`linkmgrd` functions without error on a dualtor setup testbed.
> Add port cable type getter for `MuxManager`

- objects.mk
- src/LinkMgrdMain.cpp
- src/common/MuxLogger.cpp
- src/common/MuxLogger.h
- test/FakeMuxPort.cpp
Summary:
Support store logs into a separate log file.
Add an option `-e` or `--extra_log_file`, if present, stores the logs from `linkmgrd` into `/var/log/mux/linkmgrd.log`.
Run `linkmgrd` with the option on/off
> Add a command line option to store logs into a separate file

- src/DbInterface.cpp
- src/DbInterface.h
- src/common/MuxConfig.h
- src/common/MuxPortConfig.h
- src/link_manager/LinkManagerStateMachine.cpp
- src/link_manager/LinkManagerStateMachine.h
- src/link_prober/LinkProber.cpp
- src/link_prober/LinkProber.h
- test/FakeLinkProber.cpp
- test/FakeLinkProber.h
- test/FakeMuxPort.cpp
- test/LinkManagerStateMachineTest.cpp
- test/MuxManagerTest.cpp
Original commit & PR in master branch: 
c43cf7a Jing Zhang      Tue Mar 22 16:22:00 2022 -0700  Decrease link probing interval after switchover to better determine the overhead of a toggle (#43)
Summary:
This PR is to get more accurate timestamp of when toggle completes on mux.  
The method is to decrease link probing interval to 10ms after a switchover is triggered, and write the timestamp of link prober state change to state db ```LINK_PROBE_STATS table```.
When switchover is over, revert the probing interval change. If switchover does not complete within 400ms, revert the change as well. 
To better determine the overhead of a toggle. 
Decrease link probing interval after switchover is triggered. 
Tested cases below on dual …
> Decrease link probing interval after switchover to better determine the overhead of a toggle #43

- src/link_manager/LinkManagerStateMachine.cpp
- src/link_manager/LinkManagerStateMachine.h
- src/link_manager/LinkManagerStateMachineBase.cpp
- src/link_manager/LinkManagerStateMachineBase.h
- src/link_prober/LinkProber.cpp
- src/link_prober/LinkProber.h
- test/FakeLinkProber.cpp
- test/FakeLinkProber.h
- test/FakeMuxPort.cpp
- test/LinkManagerStateMachineTest.cpp
- test/MuxManagerTest.cpp
Summary:
This PR is to address the expected behavior on default route states: 
1.	If in “manual” mode, default route state change should NOT trigger mux state change. 
2.	If in “auto” mode, default route state change to “na”, should trigger switchover to “standby”.
3.	Avoid switchovers to “active” if default route state remains “na”. 
Sign-off: Jing Zhang zhangjing@microsoft.com
To handle default route state change. Make a healthy peer always takes over when self's missing default route state. 
Shutdown heartbeats when default route state is missing and the mode is `auto`. 
Also make sure to restart the heartbeats when ToR enters manual mode or default route state is `ok`. 
Tested on dual testbeds.
> Shutdown ICMP heartbeats when default route state is missing and ToR is in `auto` mode

- src/link_manager/LinkManagerStateMachine.cpp
- test/LinkManagerStateMachineTest.cpp
Can't do a clean cherry pick from original commit & PR in master branch:
898a655 Update link prober metrics posting logics (#50)
Summary:
This PR is to post not only `link_prober_unknown_end` but also `link_prober_[active|standby]_start` metrics event to `LINK_PROBE_STATS|PORTNAME` table. Current behavior is to only post the former. 
sign-off: Jing Zhang jingzhang@microsoft.com
> Update link prober metrics posting logics #50

- src/common/MuxPortConfig.h
- src/link_manager/LinkManagerStateMachine.cpp
Summary:
Disable part of the feature introduced in #43. 
The link probing interval will NOT be decreased by default. Link prober state change events will still be posted in `LINK_PROBE_STATS|PORTNAME` in state db. 
We need to reconsider the design of this feature. 
To be more specific, this is a special case of decreasing probing interval, it's for measurement purposes only. We still want to trigger the toggle in 300ms when pack loss happens. The negative count should be 30 instead of 3 when interval is decreased to 10ms.
> Disable the feature that decreases link probe interval for measuring switch overhead

- src/common/MuxPortConfig.h
- src/link_manager/LinkManagerStateMachine.cpp
Can't cleanly cherry pick the commit from master branch: 
34a68d1 disable switchover measuring based on link prober (#49)
Summary:
Disable part of the feature introduced in #43. 
The link probing interval will NOT be decreased by default. Link prober state change events will still be posted in `LINK_PROBE_STATS|PORTNAME` in state db. 
We need to reconsider the design of this feature. 
To be more specific, this is a special case of decreasing probing interval, it's for measurement purposes only. We still want to trigger the toggle in 300ms when pack loss happens. The negative count should be 30 instead of 3 when interval is decreased to 10ms.
> Disable the feature that decreases link probe interval for measuring switch overhead #49

- src/link_manager/LinkManagerStateMachineActiveStandby.cpp
Summary:
This PR is to address the edge case that when both sides are missing default route, and standby side gets default route back. Expected behavior is standby side will switch to active. But if standby side is `wait` state when link prober is restarted, the switchover won't happen. 
sign-off: Jing Zhang [zhangjing@microsoft.com](mailto:zhangjing@microsoft.com)
When both sides are missing default route AND standby side gets default route back, we want to ensure the standby side will take over and switch to active. 
Re-initialize link prober state when default route goes from `na` to `ok`. 
Tested below scenarios: 
1. Active side missing default route. 
2. Both sides missing default route one after another.
3. Both sides missing default route, standby side get it back.
> Reset link prober state when default route is back 

- src/link_prober/LinkProber.cpp
- test/LinkProberTest.cpp
- test/LinkProberTest.h
Summary:
This PR is fix the issue when both sides' link prober is suspended, LinkManager still appears to be healthy. 
When HB suspends, TX sequence number is not updated either, hence link prober won't post an `unknown` event. 
Make sure link prober is reporting `unknown` event when it's suspended or shutdown on both sides. 
Increment sequence number even when HB is not sent. 
Tested on dualToR testbed.
> Keep incrementing sequence number when link prober is suspended and shutdown 

- src/link_manager/LinkManagerStateMachineActiveStandby.cpp
Summary:
Stemming from sonic-mgmt issue: https://github.com/Azure/sonic-mgmt/issues/5410
This is PR to lower log level of message `unsolicited MUX state change notification`.
> Lower `unsolicited MUX state change notification` log level to `WARNING`

- src/MuxPort.cpp
- src/link_manager/LinkManagerStateMachineActiveStandby.cpp
- src/link_manager/LinkManagerStateMachineActiveStandby.h
- src/link_manager/LinkManagerStateMachineBase.cpp
- src/link_manager/LinkManagerStateMachineBase.h
- test/LinkManagerStateMachineTest.cpp
Summary:
This PR is to avoid proactively switch to `active` if default route is missing. 
By proactively switching, it means:
* switches triggered by peer HB missing
* switches triggered by peer link state down 
sign-off: Jing Zhang zhangjing@microsoft.com  
ToR missing default route can't be `active healthy`. Toggling to active at this moment will only cause unwanted packet loss. 
Avoid the switch. 
Passed all sonic-mgmt `dualtor_io` tests.
> Avoid proactively switching to `active` if default route is missing 

- src/LinkMgrdMain.cpp
- src/MuxManager.cpp
- src/MuxManager.h
- src/common/MuxConfig.h
- src/common/MuxPortConfig.h
- test/LinkManagerStateMachineTest.cpp
Summary:
Add support to enable/disable the feature that decreases link prober interval. 
To have the option to enable this feature. 
Add options `--measure_switchover_overhead` , `-m` to linkmgrd process. 
1. Tested on dual testbed.
2. Passed all `dualtor_io` tests. Failed `dualtor/test_tunnel_memory_leak.py::test_tunnel_memory_leak` but noticed the same test failed on version .62.
> Add support to enable switchover time measurement (with link prober interval decreased to 10ms) feature 

- src/link_manager/LinkManagerStateMachine.cpp
- src/link_manager/LinkManagerStateMachine.h
- src/link_prober/LinkProber.cpp
- src/link_prober/LinkProber.h
- test/FakeLinkProber.cpp
- test/FakeLinkProber.h
- test/FakeMuxPort.cpp
- test/LinkManagerStateMachineTest.cpp
- test/MuxManagerTest.cpp
Summary:
Can't clear pick up this commit from master branch:
83004bf Jing Zhang      Tue Mar 29 11:33:18 2022 -0700  Shutdown ICMP heartbeats when default route state is missing and ToR is in `auto` mode (#44)
This PR is to address the expected behavior on default route states: 
1.	If in “manual” mode, default route state change should NOT trigger mux state change. 
2.	If in “auto” mode, default route state change to “na”, should trigger switchover to “standby”.
3.	Avoid switchovers to “active” if default route state remains “na”. 
Sign-off: Jing Zhang zhangjing@microsoft.com
To handle default route state change. Make a healthy peer always takes over when self's missing default route state. 
Shutdown heartbeats when default route state is missing and the mode is `auto`. …
> Shutdown ICMP heartbeats when default route state is missing and ToR is in auto mode #44

- src/link_prober/LinkProber.cpp
- test/LinkProberTest.cpp
- test/LinkProberTest.h
Unable to cherry-pick the commit below cleanly from master branch: 
13f4879 Jing Zhang      Sun Apr 3 21:56:33 2022 -0700   Keep incrementing sequence number when link prober is suspended and shutdown  (#55)
Summary:
This PR is fix the issue when both sides' link prober is suspended, LinkManager still appears to be healthy. 
When HB suspends, TX sequence number is not updated either, hence link prober won't post an `unknown` event. 
Make sure link prober is reporting `unknown` event when it's suspended or shutdown on both sides. 
Increment sequence number even when HB is not sent. 
Tested on dualToR testbed.
> Keep incrementing sequence number when link prober is suspended and shutdown #55

- src/link_manager/LinkManagerStateMachineActiveStandby.cpp
Summary:
This PR is to lower `MuxUnknown` state transition handler logs to `WARNING` level. 
It's causing noise for `LogAnalyzer`. 
Lower the log level from `ERROR` to `WARNING`.
> lower log level to warning

- src/LinkMgrdMain.cpp
- src/MuxManager.cpp
- src/MuxManager.h
- src/common/MuxConfig.h
- src/common/MuxPortConfig.h
- test/LinkManagerStateMachineTest.cpp
Can't cleanly `cherry-pick` the commit below: 
48abc9e Jing Zhang      Thu Apr 14 16:50:04 2022 -0700  Add support to enable switchover time measurement (with link prober interval decreased to 10ms) feature  (#61)
Summary:
Add support to enable/disable the feature that decreases link prober interval. 
To have the option to enable this feature. 
Add options `--measure_switchover_overhead` , `-m` to linkmgrd process. 
1. Tested on dual testbed.
2. Passed all `dualtor_io` tests. Failed `dualtor/test_tunnel_memory_leak.py::test_tunnel_memory_leak` but noticed the same test failed on version .62.
> [202012] Add support to enable switchover time measurement (with link prober interval decreased to 10ms) feature

- src/link_manager/LinkManagerStateMachineActiveStandby.cpp
Summary:
`mWaitActiveUpCount` was introduced to handle active side asymmetric link drop issue (**internal repo PR 4318425**). It helps standby ToR take over when active ToR is dropping northbound packets only. 
But in scenarios when switching to active, it's also possible that mux state notification arrives before link prober active events, hence enters `LinkProberWaitMuxActiveLinkUp` composite state. If we don't reset the count, it can lead to unnecessary heartbeat suspending. 
This issue was the root cause for credo cable 400+ ms packet loss issue. 
To avoid unnecessary heartbeat suspends. 
Reset composite state count.
Run the 2000-toggle experiment again, can't reproduce the 400+ ms HB loss issue any more.
> Reset `WaitActiveUp` count before switching to `active`

- src/MuxPort.cpp
- src/link_manager/LinkManagerStateMachine.cpp
- src/link_manager/LinkManagerStateMachine.h
- test/LinkManagerStateMachineTest.cpp
Can't cleanly `cherry-pick`  the commit below:
c4858a6 Jing Zhang      Thu Apr 14 11:27:55 2022 -0700  Avoid proactively switching to `active` if default route is missing  (#62)
Summary:
This PR is to avoid proactively switch to `active` if default route is missing. 
By proactively switching, it means:
* switches triggered by peer HB missing
* switches triggered by peer link state down 
sign-off: Jing Zhang zhangjing@microsoft.com  
ToR missing default route can't be `active healthy`. Toggling to active at this moment will only cause unwanted packet loss. 
Avoid the switch. 
Passed all sonic-mgmt `dualtor_io` tests.
> [202012] Avoid proactively switching to active if default route is missing

- src/LinkMgrdMain.cpp
- src/MuxManager.cpp
- src/MuxManager.h
- src/MuxPort.cpp
- src/common/MuxConfig.h
- src/common/MuxPortConfig.h
- test/LinkManagerStateMachineTest.cpp
Summary:
Add command line option `--default_route, -d` to enable or disable default route related feature. 
In some scenarios, users might not care if default route is missing. This PR provides options for users to disable default route related feature. 
Add support for cli option. 
Tested on dual testbed. LinkProber is shutdown only when the feature is enabled.
> Add Cli support to enable or disable default route related feature

- src/LinkMgrdMain.cpp
- src/MuxManager.cpp
- src/MuxManager.h
- src/MuxPort.cpp
- src/common/MuxConfig.h
- src/common/MuxPortConfig.h
- test/LinkManagerStateMachineTest.cpp
Can't cleanly `cherry-pick` commit below: 
7bb06fb Jing Zhang      Tue May 3 09:48:28 2022 -0700   Add Cli support to enable or disable default route related feature (#68)
Summary:
Add command line option `--default_route, -d` to enable or disable default route related feature. 
In some scenarios, users might not care if default route is missing. This PR provides options for users to disable default route related feature. 
Add support for cli option. 
Tested on dual testbed. LinkProber is shutdown only when the feature is enabled.
> [202012] Add option to enable or disable default route related feature 

- src/DbInterface.cpp
- src/MuxManager.cpp
- src/MuxManager.h
- src/MuxPort.cpp
- src/MuxPort.h
- src/common/MuxConfig.h
- src/common/MuxPortConfig.h
- src/link_manager/LinkManagerStateMachineActiveActive.cpp
- src/link_manager/LinkManagerStateMachineActiveActive.h
- src/link_manager/LinkManagerStateMachineBase.cpp
- src/link_manager/LinkManagerStateMachineBase.h
- test/MuxManagerTest.cpp
- test/MuxManagerTest.h
Summary:
Add a new field `use_known_mac` to table `LINK_PROBER`:
* if `use_known_mac` is `enable`, linkmgrd will use known mac to probe(default behavior)
* if `use_known_mac` is `disable`, linkmgrd will use server mac address from netlink
Add a new boolean attribute `mUseKnownMacActiveActive` to `MuxConfig` to represent this switch.
If `mUseKnownMacActiveActive` is `false`, the state machine will respond to server mac change.
else, the state machine will not respond to server mac change.
Pass unit test
> Support switch between using wellknown mac or server mac addr 

- src/link_manager/LinkManagerStateMachineActiveActive.cpp
- src/link_manager/LinkManagerStateMachineActiveActive.h
Summary:
1. for the mux wait timer, it will timeout waiting for the `MAX_BACKOFF_FACTOR` time after its first timeout. The timeout should increase gradually.
2. for the peer mux wait timer, it could not stop and keeps waiting:
```
[2022-05-26 10:00:56.084883] [warning] link_manager/LinkManagerStateMachineActiveActive.cpp:924 handlePeerMuxWaitTimeout: Ethernet8: Unknown timeout reason!!!, current peer mux state: Active
[2022-05-26 10:00:56.084898] [warning] link_manager/LinkManagerStateMachineActiveActive.cpp:924 handlePeerMuxWaitTimeout: Ethernet8: Unknown timeout reason!!!, current peer mux state: Active
[2022-05-26 10:00:56.084914] [warning] link_manager/LinkManagerStateMachineActiveActive.cpp:924 handlePeerMuxWaitTimeout: Ethernet8: Unknown timeout reason!!!, current …
```
> Fix mux wait timer and peer mux wait timer

- src/link_prober/LinkProberStateMachineBase.cpp
Summary:
If calling `LinkProberStateMachineBase` virtual functions, there are error logs in syslog:
```
[2022-05-26 09:13:17.210129] [error] link_prober/LinkProberStateMachineBase.cpp:230 handlePckLossRatioUpdate: Ethernet8
```
Degrade the logging level to `DEBUG`
> Degrade `LinkProberStateMachineBase` virtual function logging level

- src/DbInterface.cpp
- src/DbInterface.h
- src/MuxPort.cpp
- src/MuxPort.h
- test/FakeDbInterface.cpp
- test/FakeDbInterface.h
Summary:
This PR is to separate I2C mux state probing and gRPC forwarding state probing. 
Current implementation used the same APP DB table for active-active port forwarding state probing and active-standby port mux state probing. This is breaking CLI tests in pre-test.
1. use tables below for active-active port forwarding state probing. 
```
#define APP_FORWARDING_STATE_COMMAND_TABLE_NAME  "FORWARDING_STATE_COMMAND"
#define APP_FORWARDING_STATE_RESPONSE_TABLE_NAME "FORWARDING_STATE_RESPONSE"
```
2. `RESPONSE` table expects forwarding state response for both SELF and PEER. 
3. Rename some table names & handler functions to avoid confusion. 
Unit tests.
>  Separate I2C mux state probing and gRPC forwarding state probing 

- src/MuxPort.cpp
- src/common/MuxPortConfig.h
- src/link_manager/LinkManagerStateMachineActiveActive.cpp
- test/LinkManagerStateMachineActiveActiveTest.cpp
Summary:
Make sure self ToR is in `auto` mode before switching peer to `standby`. Also add support for `detach` mode. 
`detach` mode is equal to `auto` mode for SELF, but under this mode, ToR won't touch PEER's status. 
> Check self's mux mode before switching peer to standby & add support for `detach` mode

- src/link_prober/LinkProber.cpp
- src/link_prober/LinkProber.h
- test/LinkProberTest.cpp
- test/LinkProberTest.h
Summary:
Fix the IP header checksum error in the packet sent by `handleSendSwitchCommand`
Signed-off-by: 
Longxiang Lyu <lolv@microsoft.com> 
Jing Zhang zhangjing@microsoft.com 
Update IP header checksum after appending `TlvCommand`.
> Fix IP header checksum in handleSendSwitchCommand

- src/link_prober/LinkProber.cpp
- src/link_prober/LinkProber.h
- test/LinkProberTest.cpp
- test/LinkProberTest.h
Summary:
What is the motivation for this PR?
Fix the IP header checksum error in the packet sent by handleSendSwitchCommand
Signed-off-by:
Longxiang Lyu [lolv@microsoft.com](mailto:lolv@microsoft.com)
Jing Zhang [zhangjing@microsoft.com](mailto:zhangjing@microsoft.com)
Update IP header checksum after appending TlvCommand.
> [202012] Fix IP header checksum in `handleSendSwitchCommand`

- src/DbInterface.cpp
- src/MuxManager.h
- test/MuxManagerTest.cpp
Summary:
This PR is to avoid throwing exception when linkmgrd initializing without CONFIG DB loopback interface entry. 
Avoid unnecessary process exits. 
Log a fatal message instead of exiting the process. 
Tested on dual testbeds. Met all expected behavior below:
1. Remove loopback interface live (when linkmgrd is running):   
No linkmgrd crash. `show mux status` reported `unhealthy` as no IP interface to receive heartbeat packets.
2. Start mux service when missing loopback interface:  
No linkmgrd crash. Saw fatal log below in syslog. `show mux status` report `unhealthy`.
3. Add back loopback interface CONFIG DB entry live:  
`show mux status` reported `healthy`.
> Remove exception throwing when initializing missing loopback interface

- src/link_manager/LinkManagerStateMachineActiveActive.cpp
- src/link_manager/LinkManagerStateMachineActiveActive.h
- test/LinkManagerStateMachineActiveActiveTest.cpp
Summary:
This issue occurs when running `config load_minigraph` to load new configs at both ToRs.
After `write_standby.py`, the `muxorch` will try to direct all traffic downstream to the SoC IP and server IP to the tunnel, but `xcvrd` might fail to set the `adminforwardingstate` of the port via gRPC because the gRPC channel could not be established because the other ToR is in `standby` state.
After `linkmgrd` starts to run and receives heartbeats from itself, it will try to toggle to active[**toggle#1**], but `xcvrd` might not be able to make the hardware toggle at the moment, so `linkmgrd` will mux wait. Also, because the mux probe table is initialized with `Unknown` state, `linkmgrd` will handle the initial mux probe state to have the composite states `(active, unknown, …
> Fix inconsistent mux state

- Makefile
…r. CXX variable is used as g++ compiler.
Signed-off-by: marvell <marvell@cpss-build3.marvell.com>
For Sonic cross-compilation build (specifically for Sonic armhf built on amd64 host).
Summary:
Replaced all appearances of CC variable with CXX since CXX is used for g++ compiler. While cross-compiling your CXX variable g++ compiler will be replaced with cross-compiler g++.
> For Sonic cross-compilation build. CC variable is used as gcc compiler. CXX is used as g++ compiler.

- test/LinkManagerStateMachineActiveActiveTest.cpp
Summary:
Verify the boot up sequence:
(unknown, unknown, up) -- link prober active --> (active, unknown, up) -- toggle active, return mux unknown --> (active, unknown, up) --> probe mux, return mux unknown --> (active, unknown, up) --> probe mux, return mux active --> (active, active, up) --> toggle active again, return mux active --> (active, active, up)
Add unit test to verify the sequence.
> Add unittest to verify mux toggle active

- src/link_manager/LinkManagerStateMachineActiveActive.cpp
- src/link_manager/LinkManagerStateMachineActiveActive.h
- test/LinkManagerStateMachineActiveActiveTest.cpp
Summary:
After `config mux state active EthernetXX`, the first toggle might not be able to be succeeded as `xcvrd` has a chance to fail to setup the gRPC connection as the route changed by `muxorch` needs time to work.
The state change sequence after `linkmgrd` boots up and receives a mux config active:
(unknown, unknown, up) --> config mux active --> (unknown, active, up) --> mux state unknown[as xcvrd could not setup gRPC connection] --> (unknown, unknown, up) --> probe mux state, return unknown --> (unknown, unknown, up)
Once `linkmgrd` reaches (unknown, unknown, up), it will keep probing the mux till `xcvrd` returns either active or standby:
if the probe result is active, we need an extra toggle to active to let `show …
> Enforce another toggle after config mux to active first toggle failed

- src/DbInterface.cpp
- src/DbInterface.h
- src/LinkMgrdMain.cpp
- src/MuxManager.cpp
- src/MuxManager.h
- src/MuxPort.cpp
- src/MuxPort.h
- src/common/MuxConfig.h
- src/link_manager/LinkManagerStateMachineActiveStandby.cpp
- test/FakeDbInterface.cpp
- test/FakeDbInterface.h
- test/MuxManagerTest.cpp
- test/MuxManagerTest.h
Summary:
This PR is to add support for linkmgrd process reconciliation after warm restart. 
One step of warm reboot procedure for dual ToR is to config the switch into `manual` mode. Before warm reboot finalizer executes `config save`, we want to config the switch back into `auto` mode, so `config_db.json` will be consistent before and after the reboot. 
1. When linkmgrd is initializing, get the systemwide warm reboot flag from `WARM_RESTART_ENABLE_TABLE`. If flag == true, start a reconciliation timer. 
2. Maintenance a mux port count based on `MUX_CABLE|PORTNAME` count. When one port completes reconciliation, if warm restart flag == true, config it back into `auto` mode, reduce reconciliation port count by 1.
3. If …
> Add support for reconciliation after warm restart 

- src/link_manager/LinkManagerStateMachineActiveActive.cpp
- src/link_manager/LinkManagerStateMachineActiveStandby.cpp
- test/MuxManagerTest.cpp
- test/MuxManagerTest.h
Summary:
If blade MAC address is processed before link prober's initialization, we will expect to see the error message below. 
```
Jun  2 09:13:37.094025 str2-7260cx3-acs-13 ERR mux#linkmgrd: link_manager/LinkManagerStateMachine.cpp:640 handleGetServerMacAddressNotification: Ethernet96: failed to update Ethernet frame with mac ......
``` 
Since link prober is not initialized, of course there was no Ethernet frame to update. The blade mac will still be stored in mux port config object and will be consumed later when link prober is activated. This shouldn't be considered as an error. 
To avoid unnecessary error message, so tests won't fail for log analyzer. 
Check if link prober is initialized before logging the error message.
> Avoid unnecessary error logs from `handleGetServerMacAddressNotification`

- src/DbInterface.cpp
- src/DbInterface.h
- src/LinkMgrdMain.cpp
- src/MuxManager.cpp
- src/MuxManager.h
- src/MuxPort.cpp
- src/MuxPort.h
- src/common/MuxConfig.h
- src/link_manager/LinkManagerStateMachine.cpp
- test/FakeDbInterface.cpp
- test/FakeDbInterface.h
- test/MuxManagerTest.cpp
- test/MuxManagerTest.h
Picking up commit below from master branch:   
```9044962 Jing Zhang      Mon Jul 18 15:38:04 2022 -0700  Add support for reconciliation after warm restart  (#76)```
Summary:
This PR is to add support for linkmgrd process reconciliation after warm restart. 
One step of warm reboot procedure for dual ToR is to config the switch into `manual` mode. Before warm reboot finalizer executes `config save`, we want to config the switch back into `auto` mode, so `config_db.json` will be consistent before and after the reboot. 
1. When linkmgrd is initializing, get the systemwide warm reboot flag from `WARM_RESTART_ENABLE_TABLE`. If flag == true, start a reconciliation timer. 
2. Maintenance a mux port count based on `MUX_CABLE|PORTNAME` …
> [202012] Add support for reconciliation after warm restart  (#76)

- src/DbInterface.cpp
- src/DbInterface.h
- src/MuxManager.cpp
- src/MuxManager.h
- src/MuxPort.cpp
- src/MuxPort.h
- test/MuxManagerTest.cpp
- test/MuxManagerTest.h
Summary:
This PR is an enhancement for TSA. When the CONFIG DB entry below is added, linkmgrd should be set to `standby`. 
```
"BGP_DEVICE_GLOBAL": {
"STATE": {
"tsa_enabled": "false"
}
}
```
This PR is to enhance TSA logic, to handle the scenario when BGP_DEVICE_GLOBAL configuration is pushed directly without explicitly executing `TSA`.
Make linkmgrd listen CONFIG DB `CFG_BGP_DEVICE_GLOBAL_TABLE_NAME` table, and config mux mode to `standby` once `tsa_enabled == true`.
1. Added unit tests.
2. Tested on dual testbeds with `redis-cli -n 4 hset "BGP_DEVICE_GLOBAL|STATE" tsa_enabled true`, was able to see logs from handlers and `show mux status` switch to `standby`.
> TSA enhancement

- src/link_manager/LinkManagerStateMachineActiveActive.cpp
Summary:
This PR is to update the definition of `healthy` label in active-active set up, to remove the dependency on gRPC healthiness. 
In active-active setup, the state machine does not depend on gRPC server's healthiness any more. Hence we don't want to `show mux status` to print `unhealthy` label when receiving unexpected state notification from gRPC or when gRPC is inaccessible. 
Updated `updateMuxLinkmgrState` method to check link prober, link state & default route only.
Unit tests.
> Update the definition of `healthy` label 

- src/link_manager/LinkManagerStateMachineActiveActive.cpp
Summary:
Submitting this PR to stop considering gRPC state `standby` as `healthy`. 
When ToR-A is `healthy`, in upgrade scenario, ToR-B might go ahead with cold reboot. And if ToR-A's gRPC state is `standby` in this case, we will lose northbound traffic. 
To avoid unwanted cold reboot in upgrades. 
Stop considering gRPC state `standby` as healthy. 
Unit tests.
> [active-active] Update `unhealthy` label definition

- src/link_manager/LinkManagerStateMachineActiveStandby.cpp
- src/link_manager/LinkManagerStateMachineActiveStandby.h
- test/FakeLinkProber.cpp
- test/FakeLinkProber.h
- test/LinkManagerStateMachineTest.cpp
Summary:
This PR is to  address the overwhelming `handleMuxWaitTimeout` syslog.
1. We saw millions of `handleMuxWaitTimeout` log in 24 hours on a ToR with unhealthy interfaces, which is way too chatty and unnecessary.
1. Log only once when timing out on mux state probing (38.4 seconds). 
1. Unit tests. 
1. Tested on cluster device, didn't see the flooding messages any more.
> [Active-Standby]Remove unnecessary `handleMuxWaitTimeout` logs

- src/DbInterface.cpp
- src/DbInterface.h
- src/MuxPort.h
- test/FakeDbInterface.cpp
- test/FakeDbInterface.h
- test/FakeMuxPort.h
- test/LinkManagerStateMachineActiveActiveTest.cpp
- test/MuxManagerTest.cpp
- test/MuxManagerTest.h
Summary:
This PR is to fix race condition introduced by `wrap` method of `boost::asio::io_service::strand`: 
> In the following case:
> 
> async_op_1(..., s.wrap(a));
> async_op_2(..., s.wrap(b));
>
> the completion of the first async operation will perform s.dispatch(a), and the second will perform s.dispatch(b), but the order in which those are performed is unspecified. That is, you cannot state whether one happens-before the other. Therefore, none of the above conditions are met and no ordering guarantee is made. 
To fix the bug that linkgmrd cleans mux metrics table __after__ setting mux state to orchagent. 
1. Use ` boost::asio::post()` to replace `wrap`.
2. Add unit tests to cover this race condition scenario:
* Remove …
> Fix race condition caused by strand `wrap` method

- src/link_manager/LinkManagerStateMachineActiveStandby.cpp
- src/link_manager/LinkManagerStateMachineActiveStandby.h
Summary:
This PR is to backoff mux probing when both sides are unable to receive ICMP heartbeat. In this case, originally, state machine will do mux state probing each 300ms. It will be too much when more than one interface is having the same issue, and it will cause delay in switchovers. 
Improve switchover performance, reduce packet loss. 
* Increment backoff factor every time state machine enters 
`LinkProber: Wait/Unknown, MuxState: Active, LinkState: Up`
`LinkProber: Wait, MuxState: Standby, LinkState: Up` 
* Set mux probe timer based on the backoff factor. 
* Reset factor when exiting the state. 
Tested with 1000 switchovers. The performance improvement is comparable to fully disabling mux probing.
> Backoff mux probing for server down scenario

- test/MuxManagerTest.cpp
Summary:
The logic of `DbInterfaceRaceConditionCheck` test is loop 1000 times for the action below: 
1. post two jobs 
2. wait for 1 ms
3. assert if both jobs are completed
4. assert the execution order of two jobs
It seems like 1ms is not enough, jobs would be piled up. Even though it might eventually catch up, any of the 1000 assertion fails will lead to build failure. 
Hence incrementing time to 10ms now. 
Make unit test more stable. 
Increment waiting time for handlers to be executed. 
Build locally.
> Adjust `DbInterfaceRaceConditionCheck` to Wait Longer for Handlers to be executed 

- src/DbInterface.cpp
- src/DbInterface.h
Summary:
Fix peer toggle for `active-active` ports.
Use `table` to writes updates instead of `ProducerStateTable`.
For the peer toggle, `linkmgrd` directly talks to `ycabled` instead of `muxorch`, and `ProducerStateTable` is primarily used for interaction with `orchagent`.
Use `table` to write state updates is sufficient in this scenario.
> Use `table` to toggle peer forwarding state

- test/MuxManagerTest.cpp
Summary:
This PR is to fix flaky test `DbInterfaceRaceConditionCheck`, Even #111 extended the wait time for handlers to complete, it's still not a guarantee, this test can still be unstable. Making an enhancement now to do a busy waiting on the hander invoke counts. 
Also 202012 branch's `createPort` function uses `boost::io_service::run_one` while master uses `poll_one`. `run_one` might block the calling thread until one event is ready to process. To avoid endless handing, adjust the order of initializing thread pool & creating port object. 
Make unit test stable in image building. 
1. Busy wait on invoke count before checking. 
2. create port object before initialization of thread pools to avoid hanging. 
Build passes locally.
> Fix flaky tests `DbInterfaceRaceConditionCheck`

- src/DbInterface.cpp
- src/DbInterface.h
- src/MuxPort.h
- test/FakeDbInterface.cpp
- test/FakeDbInterface.h
- test/FakeMuxPort.h
- test/MuxManagerTest.cpp
- test/MuxManagerTest.h
3f7a6f2 Fix race condition caused by strand `wrap` method (#104)
Summary:
This PR is to fix race condition introduced by `wrap` method of `boost::asio::io_service::strand`: 
> In the following case:
> 
> async_op_1(..., s.wrap(a));
> async_op_2(..., s.wrap(b));
>
> the completion of the first async operation will perform s.dispatch(a), and the second will perform s.dispatch(b), but the order in which those are performed is unspecified. That is, you cannot state whether one happens-before the other. Therefore, none of the above conditions are met and no ordering guarantee is made. 
To fix the bug that linkgmrd cleans mux metrics table __after__ setting mux state to orchagent. 
1. Use ` boost::asio::post()` to replace `wrap`.
2. …
> [202012] Fix race condition caused by strand wrap method #104

- src/link_manager/LinkManagerStateMachineActiveActive.cpp
- test/FakeDbInterface.cpp
- test/FakeDbInterface.h
- test/FakeMuxPort.h
- test/LinkManagerStateMachineActiveActiveTest.cpp
- test/LinkManagerStateMachineActiveActiveTest.h
Summary:
Fixes #116 
Fix that `show mux status` shows `unhealthy` for `active-active` ports with heartbeats after `config load_minigraph`.
After `linkmgrd` receives default route updates, let it update its health info.
Add unit-test.
> Update linkmgr health after getting default route update

- src/link_manager/LinkManagerStateMachineActiveActive.cpp
- src/link_manager/LinkManagerStateMachineActiveStandby.h
- src/link_manager/LinkManagerStateMachineBase.h
Summary:
This PR is to fix missing mux metrics events for toggles of active-active ports. 
To store linkmgrd toggle start time and end time in state db.  
* Post mux metrics `SwitchingStart` event in `switchMuxState` function. 
* Post mux metrics `SwitchingEnd` event when receive mux state notification after toggle. 
Tested on testbeds, was able to print mux metrics and `LAST_SWITCHOVER_TIME`: 
```
:~$ show mux metrics Ethernet12
PORT        EVENT                           TIME
----------  ------------------------------  ---------------------------
Ethernet12  linkmgrd_switch_active_start    2022-Aug-17 21:21:58.897637
Ethernet12  orch_switch_active_start        2022-Aug-17 21:21:58.907666
Ethernet12  orch_switch_active_end …
```
> [active-active] post mux metrics events 

- src/link_manager/LinkManagerStateMachineActiveActive.cpp
- test/LinkManagerStateMachineActiveActiveTest.cpp
Summary:
This PR is to handle https://github.com/sonic-net/sonic-linkmgrd/issues/119
Before, how linkmgrd handles `auto` configuration is: 
1. reset link prober state, trigger state change event
2. probe mux state. 
Issue here is, if gRPC state mismatching local state \&\& mux probe notification arrives before heartbeat events, local state can remain unchanged. Example is shown in https://github.com/sonic-net/sonic-linkmgrd/issues/119
Handle toggle edge case. 
Update handle mux config logics. 
Unit tests.
> Update `handleMuxConfigNotification` logic

- src/link_manager/LinkManagerStateMachineActiveActive.cpp
- src/link_manager/LinkManagerStateMachineActiveActive.h
Summary:
This PR is to remove repeating `handlePeerMuxWaitTimeout` and `handleMuxWaitTimeout` log message. 
When printing this log, linkmgrd doesn't do a retry or state change, so it's meaningless to repeat.  
When gRPC server is down, this message will become endless and cause unwanted syslog flood. 
Remove unnecessary chatty log message. 
Stop starting mux wait timer again after first timeout. 
Existing Unit tests.
> [active-active] Remove unnecessary mux wait timeout logs

- src/link_manager/LinkManagerStateMachineActiveActive.cpp
- test/LinkManagerStateMachineActiveActiveTest.cpp
- test/LinkManagerStateMachineActiveActiveTest.h
Summary:
Fixes #127 
Fix the issue that `linkmgrd` fails to set mux config if mux config notification comes before all components are initialized.
> Fix mux config

- src/link_prober/LinkProber.cpp
Signed-off-by: maipbui <maibui@microsoft.com>
Summary: Replace insecure `memset` function in src/link_prober
`memset()` is an insecure function that can cause buffer overflow.
Replace `memset()` by zero initialization
> [linkmgrd] Replace memset function in link_prober

- src/link_manager/LinkManagerStateMachineActiveActive.cpp
- test/FakeMuxPort.cpp
- test/LinkManagerStateMachineActiveActiveTest.cpp
Summary:
This PR is to shutdown link prober if default route entry is missing when `linkmgrd` starts. So the interface can be in `standby` if the device is isolated. 
To keep isolated device in `standby`. 
Shutdown link prober if default route is missing. 
Shutdown bgp, confirmed `ROUTE_TABLE` is removed. Then restart `linkmgrd` process, `active-active` interfaces are all `standby`. Did a tcpdump, no ICMP request was sent. 
Restart bgp, confirmed `ROUTE_TABLE` is added. `active-active` interfaces are back in `active`. Did a tcpdump, ICMP request showed up.
> [active-active] shutdown link prober when starting as isolated

- src/MuxManager.cpp
- src/link_manager/LinkManagerStateMachineActiveStandby.cpp
Summary:
Per offline discussion, submitting this PR to update warm restart reconciliation logic of linkmgrd. Instead of waiting for all 3 components to reconcile, now we only need wait for LinkProber and MuxState. 
To get `linkmgrd` reconciled as soon as possible.  
Unit tests.
> [active-standby] update warmboot reconciliation logic 

- azure-pipelines.yml
- lgtm.yml
sonic-swss-common lib will add dependency to libyang soon, so need install libyang lib to prevent build and UT break.
Modify azure pipeline to install libyang in azure pipeline steps.
Pass all UT.
Modify azure pipeline to install libyang in azure pipeline steps.
> Install libyang to azure pipeline

- test/LinkManagerStateMachineActiveActiveTest.cpp
Summary:
This PR is to fix flaky unit tests. 
Make tests more stable. 
Add one more io_service run to `handleProbeMuxState('unknown') `.  If not, depending on the timing, sometimes it will have one more handler (`handleMuxWaitTimeout`) to execute and later switchover transactions can't be completed. 
Build linkmgrd.
> [Active-Active] flaky `LinkmgrdBootupSequence` unit tests

- src/DbInterface.cpp
- src/DbInterface.h
- src/MuxPort.h
- src/link_manager/LinkManagerStateMachineActiveStandby.cpp
- src/link_manager/LinkManagerStateMachineActiveStandby.h
- test/FakeDbInterface.cpp
- test/FakeDbInterface.h
- test/FakeLinkProber.cpp
- test/FakeLinkProber.h
- test/LinkManagerStateMachineTest.cpp
Summary:
In production we saw unexpected switchover happen from time to time (switchovers that were not triggered by CLI or config change), we want to know what causes the switchover when troubleshooting.  Hence submitting this PR to post switchover cause to state DB. 
sign-off: Jing Zhang
To root cause unexpected switchovers quickly. 
Introduced new table `MUX_SWITCH_CAUSE` to store switchover cause. 
* Unit tests
* Verified on DUT, causes were posted. 
```
admin@svcstr-7050-acs-1:~$ redis-cli -n 6 hgetall "MUX_SWITCH_CAUSE|Ethernet96"
1) "cause"
2) "Link_Down"
3) "time"
4) "2022-Sep-14 23:02:28.482322"
```
> Post switchover reasons to STATE DB

- src/MuxPort.cpp
- src/link_manager/LinkManagerStateMachineActiveActive.cpp
- src/link_manager/LinkManagerStateMachineActiveActive.h
- src/link_manager/LinkManagerStateMachineBase.cpp
- src/link_manager/LinkManagerStateMachineBase.h
- test/LinkManagerStateMachineActiveActiveTest.cpp
Summary:
This PR is to sync up server-side admin forwarding state in case it's out-of-date. 
To make sure server-side admin forwarding state is up to date. 
Every time ycabled gets a transient failure for gRPC connection, it writes to APP db. Make linkmgrd consume this notification: 
```
"FORWARDING_STATE_RESPONSE:PORTNAME": 
{
"response": "failure"
}
```
- If there is a gRPC request sent out earlier but not responded or timed out, do nothing. 
- It there isn't a gRPC request, do an immediate querying. 
Tested on DUT. 
When there is a gRPC request, `mWaitTimer` will is not expired, do nothing, wait for the mux state notification to trigger the action to avoid double backoff. 
```
Sep 19 20:40:45.218834 svcstr-7050-acs-1 WARNING …
```
> [Active-Active] server side admin forwarding state sync up

- src/link_manager/LinkManagerStateMachineActiveStandby.cpp
- test/LinkManagerStateMachineTest.cpp
Summary:
This is to fix the syslog flood issue caused by repeated switchovers from `unknown` to `standby`. The scenario trigged the issue was when xcvrd timed out toggles requests but was able to probe:
Linkmgrd toggles to `standby`
-> toggles fails, xcvrd writes `unknown`
-> linkmgrd probes mux state
-> xcvrd writes `standby`
-> linkmgrd toggles to `standby`  (previous mux state was `unknown`, switching to match)
-> toggles fails, xcvrd writes `unknown`
-> ... ...
Avoid the syslog flood. 
Avoid the immediate mux state probes if entering mux state `unknown`. Instead, start a mux probe timer of 300ms. 
Unit tests. 
Syslog of the issue: 
```
Jul 28 00:46:59.864911 XXXXXXXXXXXXXXXXXXXX NOTICE pmon#ycable[33]: Got a change event …
```
> [Active-Standby] fix syslog flood caused by `unkown -> standby` switchovers 

- src/link_manager/LinkManagerStateMachineActiveActive.cpp
- test/LinkManagerStateMachineActiveActiveTest.cpp
Summary:
This PR is to retry & keep the `standby` state after configuring mux mode. **It's NOT a fix for faiing to toggle standby, which we still need to investigate.**
The motivation is that, if toggle standby fails
-> later gRPC probe `active` 
-> state machine in `LinkProber==Active, Link==Up, Mux==Active`
-> consider it as a healthy state and no more action is triggered. 
But now, `show mux status` returns `standby` as linkmgrd last writes `standby`, tunnel route is added. And worst of all, we get stuck in this state unless we restart mux service, cause `config mux mode active` won't fix it as linkmgrd already consider itself in `active` and won't writes to app db to update. 
Unit tests.
> [Active-Active] Retry config mux mode standby

- src/link_manager/LinkManagerStateMachineActiveActive.cpp
- src/link_manager/LinkManagerStateMachineActiveActive.h
- src/link_manager/LinkManagerStateMachineActiveStandby.h
- src/link_manager/LinkManagerStateMachineBase.h
- src/link_prober/LinkProber.cpp
- src/link_prober/LinkProberStateMachineActiveActive.cpp
- src/link_prober/LinkProberStateMachineActiveActive.h
- test/FakeMuxPort.cpp
- test/LinkManagerStateMachineActiveActiveTest.cpp
- test/LinkManagerStateMachineActiveActiveTest.h
Summary:
This PR is to post link prober stats to state db for active-active interfaces.
Tested on DUT. 
* Init
```
admin@svcstr-7050-acs-1:~$ sudo show mux packetloss Ethernet24
PORT        COUNT                 VALUE
----------  ------------------  -------
Ethernet24  pck_loss_count            0
Ethernet24  pck_expected_count      177
PORT    EVENT    TIME
------  -------  ------
```
* Shutdown interface
```
admin@svcstr-7050-acs-1:~$ sudo config interface shutdown Ethernet24
admin@svcstr-7050-acs-1:~$ sudo show mux packetloss Ethernet24
PORT        COUNT                 VALUE
----------  ------------------  -------
Ethernet24  pck_loss_count            2
Ethernet24  pck_expected_count      207
PORT        EVENT …
```
> [Active-Active] Post link prober stats to state db 

- src/link_manager/LinkManagerStateMachineActiveActive.cpp
Summary:
I observed that in some cases shutting down bgp sessions didn't make active-active interfaces get into `standby` state. The issue was mux mode was not in `auto` mode. But actually, even in `standby` mode & `detach` mode we should still force it to toggle to `standby` (by shutting down icmp heartbeat.)
When mux mode in `standby`
Tested different mux mode with bgp sessions on and off. Heartbeats were disabled and enabled as expected.
> [Active-Active] Update default route shutdown heartbeat logic

- src/link_manager/LinkManagerStateMachineActiveStandby.cpp
- src/mux_state/MuxStateMachine.h
- src/mux_state/WaitState.cpp
- src/mux_state/WaitState.h
Summary:
This PR is to fix incorrect mux metrics timestamps caused by unsolicited mux state notification. 
Sign-off: Jing Zhang zhangjing@microsoft.com 
To avoid inaccurate `linkmgrd_switch_standby_end` timestamp. 
```
zhangjing@SJC20-0101-0712-03LT0:~$ show mux metrics Ethernet16
PORT        EVENT                          TIME
----------  -----------------------------  ---------------------------
Ethernet16  linkmgrd_switch_standby_start  2022-Sep-17 22:15:37.045516
Ethernet16  orch_switch_standby_start      2022-Sep-17 22:15:37.047081
Ethernet16  orch_switch_standby_end        2022-Sep-17 22:15:37.096656
Ethernet16  xcvrd_switch_standby_start     2022-Sep-17 22:15:37.123937
Ethernet16  xcvrd_switch_standby_end       2022-Sep-17 22:15:37.129636
Ethernet16 …
```
> [Active-Standby] avoid posting mux metrics event when receiving unsolicited mux state notification 

- src/link_manager/LinkManagerStateMachineActiveActive.cpp
- test/LinkManagerStateMachineActiveActiveTest.cpp
Summary:
Fixes #144 
After `config reload`, some ports `SERVER_STATUS` remain to be in `unknown`.
Toggle to `active` again.
Add unittest to verify the boot sequence.
> [active-active] Fix config reload

- src/link_manager/LinkManagerStateMachineActiveActive.cpp
- src/link_manager/LinkManagerStateMachineActiveActive.h
- src/link_manager/LinkManagerStateMachineBase.cpp
- src/link_manager/LinkManagerStateMachineBase.h
- src/link_prober/IcmpPayload.h
- src/link_prober/LinkProber.cpp
- src/link_prober/LinkProber.h
- src/link_prober/LinkProberStateMachineActiveActive.cpp
- src/link_prober/LinkProberStateMachineActiveActive.h
- src/link_prober/LinkProberStateMachineBase.cpp
- src/link_prober/LinkProberStateMachineBase.h
- test/FakeLinkProber.cpp
- test/FakeLinkProber.h
- test/FakeMuxPort.cpp
- test/LinkManagerStateMachineActiveActiveTest.cpp
- test/LinkProberTest.cpp
- test/LinkProberTest.h
Summary:
Fixes #143
For issue #143, if there is a link drop for upstream traffic, the ToR will try to toggle both itself and peer to `standby`. But the peer ToR might still be able to receive heartbeats and should be in `active` state.
Enable `linkmgrd` to support sending mux probe command to its peer when it tries to toggle peer to `standby`.
Add unittests and verify on real dualtor pairs.
> [active-active] Add support to send/handle mux probe request

- src/common/MuxPortConfig.h
- src/link_manager/LinkManagerStateMachineActiveActive.cpp
- src/link_manager/LinkManagerStateMachineActiveActive.h
- test/LinkManagerStateMachineActiveActiveTest.cpp
Summary:
This PR is to help recover when SoC side admin forwarding state is unexpectedly changed. 
When server side admin forwarding state is different from ToR side, we want to correct it back. 
Start a periodical update since state machine is activated. 
Tested on DUTs. RPC was called for getting every 10 seconds. 
```
Oct 31 23:38:52.708151 svcstr-7050-acs-1 WARNING mux#linkmgrd: link_manager/LinkManagerStateMachineActiveActive.cpp:406 startAdminForwardingStateSyncUpTimer: Ethernet12
Oct 31 23:39:02.708674 svcstr-7050-acs-1 WARNING mux#linkmgrd: link_manager/LinkManagerStateMachineActiveActive.cpp:419 handleAdminForwardingStateSyncUp: Ethernet12
Oct 31 23:39:02.708924 svcstr-7050-acs-1 WARNING mux#linkmgrd: …
```
> [Active-Active] periodically re-sync soc side admin forwarding state 

- src/link_prober/IcmpPayload.h
Summary:
This PR is to fix the false positive link prober `unknown` event. Sometimes we see link prober reporting heartbeat missing even when tcpdump shows not a single reply is dropped. 
Below is the debug log of a repro, `handleRecv` should have been invoked again after reading SELF's heartbeat, but it was never posted by `aync_read_some` till timeout after 100ms and another round of probing is started.  
```
[2022-10-27 07:24:11.161134] [debug] link_prober/LinkProber.cpp:380 handleRecv: Ethernet112
[2022-10-27 07:24:11.161162] [debug] link_prober/LinkProber.cpp:388 handleRecv: Ethernet112: Got data from: 10.50.144.143, size: 35
[2022-10-27 07:24:11.161205] [debug] link_prober/LinkProber.cpp:401 handleRecv: Ethernet112: Valid ICMP Packet from 10.50.144.143
[2022-10-27 …
```
> [202205] incrementing icmp buffer size

- src/DbInterface.cpp
- src/MuxManager.h
- src/common/MuxConfig.h
- src/common/MuxPortConfig.h
- src/link_prober/LinkProber.cpp
- test/MuxManagerTest.cpp
- test/MuxManagerTest.h
Summary:
We are getting `LINK_PROBER_STATS` onboard to stream telemetry, 300ms interval is too much for this message. 
sign-off: Jing Zhang
> [active-standby][active-active] update link prober stats updating frequency to 30s

- src/MuxManager.h
- src/common/BoostAsioBehavior.h
- src/common/MuxConfig.h
- src/common/StateMachine.h
- src/link_prober/LinkProber.h
- test/FakeLinkProber.cpp
- test/FakeMuxPort.h
Summary:
This is to address to https://github.com/sonic-net/sonic-linkmgrd/issues/153
Needed strand count: 
```
(1 for link prober + 4 for state machines + 1 for mux port) * (# of ports) + 1 for DbInterface + 1 for MuxManager
```
> [active-active] Incrementing `BOOST_ASIO_STRAND_IMPLEMENTATIONS`

- src/MuxManager.cpp
- src/link_manager/LinkManagerStateMachineActiveActive.cpp
- test/LinkManagerStateMachineActiveActiveTest.cpp
Summary:
This RP is to remove the chatty messages below: 
```
"trimmed_message": ******************** mux#linkmgrd: link_manager/LinkManagerStateMachineActiveActive.cpp:329 handlePeerMuxStateNotification: Ethernet16: app/state db mux state: Unknown,
"count_": 70131
"trimmed_message": ******************** mux#linkmgrd: link_manager/LinkManagerStateMachineActiveActive.cpp:263 handleProbeMuxStateNotification: Ethernet16: app db mux state: Unknown,
"count_": 67479
"trimmed_message": ******************** mux#linkmgrd: MuxManager.cpp:275 addOrUpdatePeerLinkState: Ethernet108: peer link state unknown,
"count_": 6886
```
linkmgrd will still log warning level message if the state changes or triggers a toggle. 
Remove unnecessary warning …
> [Active-Active] remove chatty messages

- src/DbInterface.cpp
- src/link_manager/LinkManagerStateMachine.cpp
- test/LinkManagerStateMachineTest.cpp
Summary:
This PR is to address the agreement with Streaming Telemetry team on onboarding link prober packet loss data:
1. keep only state transition event in the table (each message)
2. batch update counters to avoid separate messages, i.e. `pck_expected_count` and `pck_loss_count` should be update in one transaction. 
To simplify message processing on Streaming Telemetry side. 
Stop icmp_responder:
```
admin@svcstr-7050-acs-1:~$ show mux packetloss Ethernet4
PORT       COUNT                 VALUE
---------  ------------------  -------
Ethernet4  pck_expected_count     1600
Ethernet4  pck_loss_count          367
PORT       EVENT                      TIME
---------  -------------------------  --------------------------- …
```
> [202012] Update link prober stats post logic #159

- src/link_manager/LinkManagerStateMachineActiveActive.cpp
- test/LinkManagerStateMachineActiveActiveTest.cpp
Summary:
Fixes #165
Fix issue: https://github.com/sonic-net/sonic-linkmgrd/issues/165
Reset the link prober state if the mux state is unknown when the mux config is changed back from `active` or `standby` to `auto`.
> Fix mux config when gRPC connection is lost

- src/link_manager/LinkManagerStateMachineActiveActive.cpp
- src/link_manager/LinkManagerStateMachineActiveActive.h
- test/LinkManagerStateMachineActiveActiveTest.cpp
Summary:
To fix issue #168. 
In the failure scenario, the event sequence was 
- write_standby set state to "active" when services restarted
- mux config `auto`
- init link state `down`
- init mux state `unknown`
- state machine activated, re-init link prober state to (wait, wait, down)
- link prober state event: unknown, supposed to switch to `standby`, but there wasn't transaction handler defined for "unknown, unknown, down" or  "unknown, wait, down"
The fix here is to define no-op handlers to enforce a `standby` state or a state probing. 
sign-off: Jing Zhang zhangjing@microsoft.com. 
To switch `active` interface into `standby` if link state is down after booting up. 
Define link down related state transition handlers. 
Tested on active-active dualtor, `show mux status` …
> [active-active] fix issue that interfaces get stuck in `active` if service starts up with link state down

- src/link_manager/LinkManagerStateMachineActiveActive.cpp
- test/LinkManagerStateMachineActiveActiveTest.cpp
Summary:
To avoid extra disruption after a BGP shutdown.
The reason is that, after a BGP shutdown, `linkmgrd` will stop heartbeats, and both local ToR and peer ToR will receive the heartbeat missing and toggle the local ToR to standby.
There is a chance that the peer ToR toggles local ToR to standby first, and the local ToR will probe the mux finding that itself mux state as `standby`, the local ToR will toggle itself back to active. When the local ToR receives the link prober unknown event, it will toggle itself into `standby` at last.
The event sequence:
When `linkmgrd` receives default route missing event, make an extra toggle to `standby`, so local ToR's toggle to standby should be earlier than peer ToR's.
And the …
> [active-active] Toggle to standby if default route is missing

- src/link_manager/LinkManagerStateMachineActiveStandby.cpp
- test/LinkManagerStateMachineTest.cpp
Summary:
Fixes #172
Fix the issue that in the link down scenario, if config active then back auto, the mux state could be changed into standby.
Make an extra toggle in this case.
> [active-standby] Toggle to standby if link down and config auto

- src/link_manager/LinkManagerStateMachineActiveActive.cpp
- test/LinkManagerStateMachineActiveActiveTest.cpp
Summary:
Fix #174. 
Unit tests.
> [active-active] link operational down didn't trigger toggle to standby if `MuxUnknown` event arrives first. 

- src/link_manager/LinkManagerStateMachineActiveStandby.cpp
Summary:
This is to fix the edge case when link down event comes after mux probing/toggling failure. 
The switchover still needs to happen to keep orchagent state up-to-date. 
This edge case causes both side active and traffic drop.
UTs.
> [active-standby] update the check before toggling standby for link down 

- src/link_manager/LinkManagerStateMachine.cpp
Summary:
After cherry-picked PR https://github.com/sonic-net/sonic-linkmgrd/pull/173 into 202012 branch, the branch build started failing. 
It was because the commit introduced a reference to `ActiveStandbyStateMachine`: 
https://github.com/sonic-net/sonic-linkmgrd/blob/d893be9be2744ecd8bdbb0e3e102914d6ca32a55/src/link_manager/LinkManagerStateMachine.cpp#L833
> [202012] Fix build failure introduced by cherry-pick of #173

- src/link_manager/LinkManagerStateMachine.cpp
- test/MuxManagerTest.cpp
- test/MuxManagerTest.h
Summary:
Cherry-pick conflict: 
945b107 Jing Zhang      Thu Jul 21 10:16:53 2022 -0700  Avoid unnecessary error logs from `handleGetServerMacAddressNotification` (#96)
> [202012] Avoid unnecessary error logs from `handleGetServerMacAddressNotification` #96

- src/DbInterface.cpp
- src/link_manager/LinkManagerStateMachineActiveStandby.cpp
- src/link_manager/LinkManagerStateMachineActiveStandby.h
- test/LinkManagerStateMachineTest.cpp
Summary:
Fixing a common issue in production. Root cause is bad firmware failing to respond to mux toggle or mux query. 
For example, in below senario, we will have two `standby` ToRs in the end, both sides will have tunnel-route installed. 
``` 
UT0: active -> toggle standby -> toggles succeeds -> healthy 
LT0: standby > receive heartbeat event active due to peer's toggle -> probe mux state -> mux state unknown -> probe mux state -> repeating ...
```
The traffic loss in this scenario is evitable, as heartbeat behavior is very consistent and from that linkmgrd should be table to tell the current mux direction. 
The solution is when mux probing is the **ONLY** failing component, linkmgrd enforce a switchover based on heartbeat status. To ensure the heartbeat behaviour is …
> [active-standby] Enforce switchover based on heartbeats when mux probe keeps failing

- src/link_manager/LinkManagerStateMachineActiveStandby.cpp
- test/LinkManagerStateMachineTest.cpp
Summary:
Issue was found in recent upgrade: ycable firmware would return `active` or `standby` to both sides. Hence one side limkgrd state will be `unhealthy` and block upgrade. 
This PR is to unblock upgrade by avoiding an immediate mux probe. Instead, wait for 300ms and if there is an inconsistency then, probe mux state. 
Cable firmware update or fix is out of the scope of this PR. 
Unblock production upgrade.
> [active-standby] avoid unnecessary mux state probe after configuring to `auto`

- src/link_manager/LinkManagerStateMachineActiveActive.cpp
- src/link_manager/LinkManagerStateMachineActiveActive.h
- test/LinkManagerStateMachineActiveActiveTest.cpp
Summary:
If the mux is healthy(`active`, `active`, `up`), mux probe `unknown` will transit the mux into `unhealthy`.
Based on the mux health definition from PR: https://github.com/sonic-net/sonic-linkmgrd/pull/163, if the mux server is not responsive, the mux should remain healthy in such a case.
1. if the mux port is healthy and the last mux notification is `unknown` from mux probe, ignore it in the health calculation.
2. add the healthy check in the periodical probe test case
3. add three more test case to cover more scenarios:
* mux active, periodical probe unknown
* mux standby, periodical probe active
* mux standby, periodical probe unknown
> Ignore mux probe unknown for health calculation

- src/MuxManager.cpp
Summary:
Remove chatty syslog message for peer link state. The state is updated by pmon every 30s even without changing. 
> [202012] remove chatty log message for peer link event

- src/link_manager/LinkManagerStateMachineActiveActive.cpp
- test/LinkManagerStateMachineActiveActiveTest.cpp
Summary:
There is no uniform mux server state correction for the state machine in
case if the mux toggle fails at first(mux server state not expected).
Let's add an uniform mux server state correction that is compatible with
previous codes.
The basic idea is that, when the mux probe is able to return meaningful
mux states(`active` or `standby`), let's add a check to see if the last toggle
succeeded or not. So let's define our mux toggle decision process as the
following:
```
If mux config is active or standby:
if last toggle success:
NOOP
else:
toggle based on the mux config
else:
if mux status not matches heartbeats:
toggle based on heartbeats
else:
if last toggle success:
NOOP
else:
toggle based on the heartbeats
```
As we only consider mux probe `active` or `standby`, …
> [active-active] Add mux server state correction mechanism

- Makefile
Summary:
Fixes #196 
Enable `docker-mux-dbg` to have correct debug symbol files.
As Debian passes debug options via environment variable `CXXFLAGS` or `CFLAGS` during package build, so let's add `-g` to the `CPP_FLAGS` if `CXXFLAGS` contains `-g`. So the final `linkmgrd` binary could have debug symbols.
use `sonic-buildimage` to build target `target/debs/bullseye/sonic-linkmgrd-dbgsym_1.0.0-1_amd64.deb`, and verify the symbol files:
```
$ ls -lah usr/lib/debug/.build-id/48/619bee180a75bafa2b1ee64a5a26c8c00ad0fe.debug
-rw-r--r-- 1 lolv lolv 11M Oct 26  2020 usr/lib/debug/.build-id/48/619bee180a75bafa2b1ee64a5a26c8c00ad0fe.debug
$ ls -lah usr/sbin/linkmgrd
-rwxr-xr-x 1 lolv lolv 998K Oct 26  2020 usr/sbin/linkmgrd
```
```
(gdb) exec-file …
```
> Enable debug symbols

- azure-pipelines.yml
- src/DbInterface.cpp
- src/link_manager/LinkManagerStateMachine.cpp
- src/link_manager/LinkManagerStateMachine.h
- test/LinkManagerStateMachineTest.cpp
Cherry-pick conflict for #184.
Summary:
Fixing a common issue in production. Root cause is bad firmware failing to respond to mux toggle or mux query.
For example, in below senario, we will have two `standby` ToRs in the end, both sides will have tunnel-route installed.
```
UT0: active -> toggle standby -> toggles succeeds -> healthy
LT0: standby > receive heartbeat event active due to peer's toggle -> probe mux state -> mux state unknown -> probe mux state -> repeating ...
```
The traffic loss in this scenario is evitable, as heartbeat behavior is very consistent and from that linkmgrd should be table to tell the current mux direction.
The solution is when mux probing is the **ONLY** failing component, linkmgrd enforce a switchover based on heartbeat status. To ensure the …
> [202012][active-standby] Enforce switchover based on heartbeats when mux probe keeps failing #184

- .github/workflows/codeql-analysis.yml
Summary:
This PR is to fix CodeQL failures. The issue was due to hard coded line numbers in `sed` commands. The `sed` commands were used to update `Makefile`, and `Makefile` has been changed recently, causing the line numbers to be off. 
To unblock PR merging. 
Use `/a` to append new lines. 
Tested with the new `sed` commands, lines were added as expected.
> [codeql] remove hard coded line numbers in `sed` commands

- src/link_manager/LinkManagerStateMachineActiveActive.h
- src/link_manager/LinkManagerStateMachineActiveStandby.cpp
- src/link_manager/LinkManagerStateMachineActiveStandby.h
- src/link_manager/LinkManagerStateMachineBase.h
- test/LinkManagerStateMachineTest.cpp
Summary:
Noticed an issue in BSL scenario that, both ToRs were be in `standby` state after mux service restart or reboot. The issue was due to no mux probe was triggered by linkmgrd. 
Root cause was link manager state machine corner case: 
* State machine activated as standby healthy after reboot or service restart
```
Apr 21 21:24:11.563419 - WARNING mux#linkmgrd: link_manager/LinkManagerStateMachine.cpp:478 activateStateMachine: Ethernet124: (P: Unknown, M: Standby, L: Up) -> (P: Standby, M: Standby, L: Up)
Apr 21 21:24:11.580274 - WARNING mux#linkmgrd: link_manager/LinkManagerStateMachine.cpp:291 setLabel: Ethernet124: Linkmgrd state is: Standby Healthy
```
* There is no heartbeat in L2 mode
```
Apr 21 21:24:11.889344 - WARNING mux#linkmgrd: …
```
> [active-standby][bsl] fix no mux probe issue

- azure-pipelines.yml
- src/DbInterface.cpp
- src/LinkMgrdMain.cpp
- src/common/MuxLogger.cpp
- src/common/MuxLogger.h
- src/common/SwssLogBackend.cpp
- src/common/SwssLogBackend.h
- src/common/subdir.mk
- test/MuxLoggerTest.cpp
- test/MuxLoggerTest.h
- test/subdir.mk
Summary:
To support linking to swss logger.
1. add a dedicated sink `SwssSyslogBackend` to direct all logs from mux logger to swss logger.
2. add custom log db observer to receive log level changes from `swssloglevel`
* This depends on: https://github.com/sonic-net/sonic-swss-common/pull/766
Manual validation on the testbed.
> Support linking to swss logger

- src/common/AsyncEvent.h
- src/link_manager/LinkManagerStateMachineActiveActive.cpp
- src/link_manager/LinkManagerStateMachineActiveActive.h
- test/FakeMuxPort.cpp
- test/LinkManagerStateMachineActiveActiveTest.cpp
- test/LinkManagerStateMachineActiveActiveTest.h
Summary:
During a config reload, mux config notification is always received before state machine init, and the state machine will not do a toggle based on the mux config after state machine init. Let's enable the state machine to re-handle the mux config notification after the state machine init and do a toggle based on the mux config.
MSFT:ADO: 17708339
1. Add a class `AsyncEvent` that could act as an event that could execute registered callbacks if the event is notified.
2.  Define `ActiveActiveStateMachine::mWaitStateMachineInit`(of `AsyncEvent`) as a wait event to register any mux config notification received before state machine init.
3. Notify the wait event `ActiveActiveStateMachine::mWaitStateMachineInit` when …
> Re-handle pre-init mux config notification after state machine init

- src/link_manager/LinkManagerStateMachineActiveStandby.cpp
- test/LinkManagerStateMachineTest.cpp
Summary:
When default route is not present, the mux port should be `unhealthy`
- Microsoft ADO **(number only)**: 24625736
When the default route is handled, update the mux health.
UT
> [active-standby] Write `unhealthy` if default route `N/A`

- src/link_prober/LinkProber.cpp
Summary:
As the subject.
Work item tracking
Microsoft ADO (number only): 24609952
Increase log level to warning so probe pause/restart could be observed in syslog.
> [link prober] Increase pause/restart probe log verbosity

- src/link_manager/LinkManagerStateMachineActiveStandby.cpp
- src/link_manager/LinkManagerStateMachineActiveStandby.h
- src/link_prober/LinkProberStateMachineBase.cpp
- src/link_prober/LinkProberStateMachineBase.h
- test/LinkManagerStateMachineTest.cpp
- test/LinkManagerStateMachineTest.h
Summary:
Fixes #217
Fix the issue that an extra mux toggle is observed when the standby ToR does a config reload.
Two reasons:
1. extra toggle due to link prober init to `unknown` when the mux is `wait`
The state transitions are:
(`unknown`, `standby`, `down`) --  activate state machine -->
(`standby`, `standby`, `down`) --> link prober `unknown` -->
(`unknown`, `standby`, `down`) --> enter mux `wait` and probe mux -->
(`unknown`, `wait`, `down`) --> port `up` -->
(`unknown`, `wait`, `up`) --> mux probe `standby` -->
(`unknown`, `standby`, `up`) --> **toggle to active** 
2. extra toggle due to the port `up` event arriving within the link prober `unknown` detection period
- Microsoft ADO **(number only)**:  24794476
1. when the port `up` …
> [active-standby] Fix extra toggle observed in `config reload`

- src/MuxManager.cpp
Summary:
This PR is to fix a warmboot bug that when linkmgrd reconciliation times out, some interfaces are left in `manual` mode. 
To make sure all interfaces have correct muxcable config. 
24911432
Run cli when timeout handler is called. 
1. Ran warmboot with healthy dualtor DUT.
2. Ran warmboot with unhealthy dualtor DUT. 
Both cases passed.
> [warmboot] config all interfaces back to `auto` if reconciliation times out 

- src/DbInterface.cpp
- src/common/MuxConfig.h
- src/common/MuxPortConfig.h
- src/link_manager/LinkManagerStateMachineActiveStandby.cpp
- src/link_manager/LinkManagerStateMachineActiveStandby.h
- test/LinkManagerStateMachineTest.cpp
Summary:
This PR is to cover an extreme edge case when none of the dualtors can receive ICMP heartbeat. The goal is to oscillate mux direction between two sides so if one side recovers, mux direction can have a chance to park on this side. 
**Note** that toggles in an unhealthy scenario like this will cause longer disruption than in a healthy scenario. 
To avoid mux direction from being parked on one side when missing heartbeat. 
25367027
**TODO:** will submit a separate PR for option to disable oscillation or increase interval. 
1. Start a 5-min timer on active side when heartbeat is missing;
2. When timer expires if still missing heartbeat && still active, toggle to standby.
Run the change …
> [active-standby] Add oscillation logic when there is no heartbeat on both sides

- src/DbInterface.cpp
Summary:
Linkmgrd unit tests overrides DbInterface functions with fake handlers and verified the invoking counters instead of interacting with real Redis Dbs. 
Hence, excluding Dbinterface.cpp from coverage checker. 
16576022
> Exclude `DbInterface` in PR coverage check

- src/link_manager/LinkManagerStateMachineActiveStandby.cpp
- src/link_manager/LinkManagerStateMachineActiveStandby.h
- test/LinkManagerStateMachineTest.cpp
- test/MuxManagerTest.cpp
Summary:
This is to fix the `show mux status` inconsistency introduced by orchagent roll back. 
In mux port state machine design, linkmgrd honors hardware state for active-standby ports, and never intends to trigger a secondary toggle when everything is healthy. But after we introduce orchagent rollback, `show mux status` can return unmatched APP_DB and STATE_DB entries for this, which blocks upgrade. 
Hence, submitting this PR as a workaround.  
26136887
> [active-standby] Fix `show mux status` inconsistency introduced by orchagent rollback 

- src/link_manager/LinkManagerStateMachineActiveStandby.cpp
- src/link_manager/LinkManagerStateMachineActiveStandby.h
- test/LinkManagerStateMachineTest.cpp
- test/MuxManagerTest.cpp
…chagent rollback  (#225)
Approach
What is the motivation for this PR?
This is to fix the show mux status inconsistency introduced by orchagent roll back.
In mux port state machine design, linkmgrd honors hardware state for active-standby ports, and never intends to trigger a secondary toggle when everything is healthy. But after we introduce orchagent rollback, show mux status can return unmatched APP_DB and STATE_DB entries for this, which blocks upgrade.
Hence, submitting this PR as a workaround.
Work item tracking
Microsoft ADO (number only):
26136887
How did you do it?
How did you verify/test it?
Summary:
> [active-standby][202205] Fix `show mux status` inconsistency introduced by orchagent rollback

- src/link_manager/LinkManagerStateMachineActiveStandby.cpp
- src/link_manager/LinkManagerStateMachineActiveStandby.h
- src/link_prober/LinkProber.cpp
- src/link_prober/LinkProber.h
- test/FakeLinkProber.cpp
- test/FakeLinkProber.h
- test/FakeMuxPort.cpp
- test/LinkManagerStateMachineTest.cpp
Summary:
Fixes #208
Fix the issue:
After the link probe `unknown`, the `standby` ToR fails to take the link.
When the link recovers, the `active` ToR is stuck in heartbeat suspension.
- Microsoft ADO **(number only)**: 26281338
Let's probe the link in suspension timeout if current state is (unknown, active, up).
Kudos to @zjswhhh to point out we should force sending the heartbeat in link detect.
UT and verify on testbed.
> [active-standby] Probe the link in suspend timeout

- src/link_manager/LinkManagerStateMachineActiveStandby.cpp
Summary:
This PR is to address consistency in PXE boot scenario. In PXE boot, there is no ICMP heartbeats. During booting up, `standby` might switch to `active`. Mux probing is now the only way to find out mux toggles. But it's also expected to see mux probing fail when link is down, backoff factor can already be maximum when link is up. 
If we don't reset backoff factor, it might take ~40s for peer to correct the inconsistency. 
467321367
> [active-standby] reset mux probing backoff factor in link flaps

- src/DbInterface.cpp
- src/MuxManager.h
- src/common/MuxConfig.h
- src/common/MuxPortConfig.h
- src/link_manager/LinkManagerStateMachineActiveStandby.cpp
- test/MuxManagerTest.cpp
- test/MuxManagerTest.h
Summary:
Add knob to enable/disable oscillation.
To avoid test flakiness. 
 
- 28187403
1. Add DB interface to enable/disable the oscillation feature
2. Add DB interface to config the oscillation interval 
Tested on lab device: 
1.  Knob was default on 
2.  Turned it off
3. Turned it on
4. Changed the interval
> [active-standby] add knob to enable/disable oscillation 

- src/MuxPort.cpp
- test/FakeMuxPort.h
- test/LinkManagerStateMachineTest.cpp
- test/LinkManagerStateMachineTest.h
Summary:
Fix the race condition of the default route notification.
This is similar to https://github.com/sonic-net/sonic-linkmgrd/pull/104
If there are multiple default route notifications received by `linkmgrd`, the mux port posts the default route handlers wrapped by strand. But boost asio doesn't guarantee the execution order of the default route handlers, so the final state machine default route could be any intermediate default route state.
For example, for default route notifications like:
```
[2024-06-20 08:28:57.872911] [warning] MuxPort.cpp:365 handleDefaultRouteState: port: EtherTest01, state db default route state: na
[2024-06-20 08:28:57.872954] [warning] MuxPort.cpp:365 handleDefaultRouteState: port: EtherTest01, state db default route state: ok
```
The final …
> [active-standby] Fix default route handler race condition

- test/LinkManagerStateMachineTest.cpp
Summary:
Fix the UT failure introduced by https://github.com/sonic-net/sonic-linkmgrd/pull/254.
The failure is due to that, the wait time for the two default route handlers to finish is 10ms, which is not sufficient on some build image agents which has limited CPU resource.
- Microsoft ADO **(number only)**: 28471183
Let's increase the wait time to 8s.
UT passed.
> Fix default route race condition UT

- src/link_manager/LinkManagerStateMachineActiveStandby.cpp
- src/link_manager/LinkManagerStateMachineActiveStandby.h
- test/LinkManagerStateMachineTest.cpp
Summary:
Fixes #253
Fix the unexpected toggle introduced by the oscillation logic.
- Microsoft ADO **(number only)**: 28397786
The oscillation is introduced to allow the active side to toggle to standby if no heartbeat is received.
The workflow is described as the following:
```
(wait, active, up) ---> set oscillation timer [1]
...
(wait, active, up) ---> (wait, wait, up) [2]
(wait, wait, up) ---> (wait, active, up)
...
(wait, active, up) <--- oscillation timer expires, toggle to standby [3]
```
[1]: the ToR enters `(wait, active, up)`, no heartbeats received, oscillation timer is set.
[2]: the ToR consistently probes the mux status, and transits between `(wait, active, up)` and `(wait, wait, up)`.
[3]: when the oscillation timer expires …
> [active-standby] Fix the oscillation logic

- src/link_prober/LinkProber.cpp
- src/link_prober/LinkProber.h
- test/LinkProberTest.cpp
- test/LinkProberTest.h
Summary:
Print out error code message when `sendHeartbeat` fails.
> [link prober] print out error code message when `sendHeartbeat` fails

- test/LinkManagerStateMachineTest.cpp
Summary:
Approach
What is the motivation for this PR?
Fix the UT failure introduced by https://github.com/sonic-net/sonic-linkmgrd/pull/254.
The failure is due to that, the wait time for the two default route handlers to finish is 10ms, which is not sufficient on some build image agents which has limited CPU resource.
Signed-off-by: Longxiang Lyu [lolv@microsoft.com](mailto:lolv@microsoft.com)
Work item tracking
Microsoft ADO (number only): 28471183
How did you do it?
Let's increase the wait time to 8s.
How did you verify/test it?
UT passed.
Any platform specific information?
Documentation
> Fix default route race condition UT (#258)

- src/link_manager/LinkManagerStateMachineActiveActive.cpp
- test/LinkManagerStateMachineActiveActiveTest.cpp
Summary:
Fixes https://github.com/sonic-net/sonic-linkmgrd/issues/278
Fix the extra toggle after the default route `N/A`.
```
(active, active, up), ok                        <- default route n/a
-> toggle to standby
(active, standby, up), n/a                      <- mux probe active from the periodically probe
(active, active, up), n/a                       <- mux state standby returned from the toggle to standby
(active, standby, up), n/a                      -> toggle to active
(active, active, up), n/a                       <- mux state active returned from the toggle to active
(active, active, up), n/a                       <- link prober unknown
(unknown, active, up), n/a                      -> toggle to standby
(unknown, standby, up), n/a                     <- mux …
```
> [active-active] Fix extra toggle after default route N/A

- src/link_manager/LinkManagerStateMachineActiveActive.cpp
- test/LinkManagerStateMachineActiveActiveTest.cpp
Summary:
Enforce switchover when target state is `standby` AND mux mode is `standby`. 
Soc agent can always restart and set the forwarding state to default "active" on host side. If this happens during ToR maintenance ( mux mode != `auto`), we still need to correct the state to "standby". 
30158450
UT
> Enforce switchover when target state is `standby` AND mux mode is `standby`

- src/DbInterface.cpp
- src/MuxManager.cpp
- src/MuxManager.h
- src/MuxPort.cpp
- src/MuxPort.h
- src/link_manager/LinkManagerStateMachineActiveStandby.cpp
- src/link_manager/LinkManagerStateMachineActiveStandby.h
- src/link_manager/LinkManagerStateMachineBase.cpp
- src/link_manager/LinkManagerStateMachineBase.h
- src/link_prober/LinkProber.cpp
- src/link_prober/LinkProber.h
- test/FakeMuxPort.h
- test/LinkManagerStateMachineActiveActiveTest.cpp
- test/LinkManagerStateMachineActiveActiveTest.h
- test/LinkManagerStateMachineTest.cpp
- test/LinkManagerStateMachineTest.h
- test/MuxManagerTest.cpp
Summary:
This is inspired from https://github.com/sonic-net/sonic-mgmt/pull/16878; the active side could be stuck in the following loop if it cannot receive any heartbeats:
```
```
and the suspend timeout will backoff with max timeout as `128 * (negative retry + 1) * send interval`; during this period, the mux port is unable to detect link failures as no heartbeats sending.
This PR is to support reset the suspend timer/backoff.
- Microsoft ADO **(number only)**: 31339123
Support reset heartbeat suspend timer for `active-standby` state machine.
UT
> [active-standby] support reset heartbeat suspend timer

- src/link_manager/LinkManagerStateMachineActiveStandby.cpp
Summary:
Noticed that if server does serving during LT0 ugprade, link flaps on both sides' ToR, T0 can't always take over as `active` after link is up. Cause in some cases the `shutdownTx` was skipped on LT0 due to state machine inactivated or `tsa_enabled` made mux mode `standby`. Logs attached in internal ADO. 
Adding a similar fix to https://github.com/sonic-net/sonic-linkmgrd/pull/130 for active-standby as well. 
32099536
UTs
> [active-standby] shutdown link prober when starting as isolated

- src/link_manager/LinkManagerStateMachineActiveActive.cpp
- test/LinkManagerStateMachineActiveActiveTest.cpp
Summary:
Cherry-pick https://github.com/sonic-net/sonic-linkmgrd/pull/291 into 202411
Signed-off-by: Longxiang Lyu lolv@microsoft.com
> [202411][active-active] Fix mux not toggle to active in default route flapping (#291)

- src/link_prober/LinkProberBase.cpp
This log should only for debug purpose because its in read function itself it will print for duplicate or already set guid as well. 
So changing the log level to debug.
Summary:
> Change the log level for reading Guid from icmp payload

- src/link_prober/LinkProberBase.cpp
- src/link_prober/LinkProberBase.h
- test/MockLinkProberTest.cpp
- test/MockLinkProberTest.h
Summary:
Fix #307 
The mux port health is `uninitialized` in nightly.
And from the syslog, the state machines are not activated as the link probers are trying to generate `GUID`. The `GUID` generation logic is stuck somehow in the multi-threading environment.
From the backtrace on each threads, some threads is busy looping the generated `GUID` set while some threads are trying to insert new `GUID` into the set; this is a race condition as the C++ multiset is not thread-safe.
- Microsoft ADO **(number only)**: 34335369
Let's wrap the generated `GUID` set update/read code section with a lock.
1. UT.
2. use the script in the issue, run over 12h, no repro.
> Fix mux port `uninitialized`
