sonic-net/sonic-linkmgrd

azure-pipelines.yml

Signed-off-by: Guohan Lu <lguohan@gmail.com>

[ci]: use native arm64/armhf build

---

azure-pipelines.yml

Add support for code diff coverage.
signed-off-by: Jing Zhang zhangjing@microsoft.com
Tested with the code block below to verify if azp code diff coverage was working. 
```  
int i = 0;
if (i == 1){
i = 0; // not covered
}
```

Support code diff coverage

---

README.md

Summary:
Update README. Setting some simple guidance for coding style.
Signed-off-by: Ying Xie <ying.xie@microsoft.com>

[linkmgrd] update README, set coding style guidance

---

Makefile

Summary:
`make clean` should delete the test result report `.xml` file created by `make test`
Delete the test report in `make clean`.
Run `make clean` after `make test`.

Improve `make clean`

---

.clang-format

Summary:
[`clang-format`](https://clang.llvm.org/docs/ClangFormat.html) is used to format cpp files.
This PR add repo-level clang format config file so repo contributor could format there changes to meet the repo requirement listed in [`README`](https://github.com/Azure/sonic-linkmgrd/blob/master/README.md).
To use this, please install `clang-format` on your machine and relevant `clang-format` plugins for your IDE.
To install the latest `clang-format` on ubuntu, please add package repos: https://apt.llvm.org/
For `vs-code` users, please add `clang-format` plugin: https://marketplace.visualstudio.com/items?itemName=xaver.clang-format
Format a `cpp` file and check if the format follows the rules specified in `README.md`

Add repo level clang format config file

---

.clang-format

Summary:
Fix current `clang-format` file:
1. disable includes sorting
2. always put class braces into a new line.

Enhance clang format

---

doc/default_route.md

Summary:
Realizing the default route related changes is actually affecting linkmgrd's state transition logics. Adding a doc for future reference. 

Add doc for default route related changes 

---

azure-pipelines.yml

Summary:
Setting diff coverage threshold to 80% to meet code quality requirement. 
Current code coverage is: 
4034 of 4999 lines covered (80.70%)
Run Azure pipeline.

[ci]: uplift diff coverage threshold to 80%

---

objects.mk
src/LinkMgrdMain.cpp
src/common/MuxLogger.cpp
src/common/MuxLogger.h
test/FakeMuxPort.cpp

Summary:
To have PR: #41 into 202012 branch.
Cherry-pick #41 and fix conflicts.

[202012] Add a command line option to store logs into a separate file

---

src/link_manager/LinkManagerStateMachineActiveActive.cpp

Summary:
Fix peer mux wait timer.
Fix the typo.

Fix peer mux wait back off factor

---

test/FakeLinkProber.cpp

Summary:
This PR is to fix build failure introduced by commit [847c1e8](https://github.com/sonic-net/sonic-linkmgrd/commit/847c1e83c20863d932c7f6071383d2753cfdb1c6).
Fix build failure. 
Remove usage of undefined base class. 
Build passed locally.

Fix build failure introduced by commit `847c1e8`

---

lgtm.yml

Summary:
Fix lgtm failure for error below:  
`fatal error: uuid/uuid.h: No such file or directory`

Fix lgtm `fatal error: uuid/uuid.h: No such file or directory`

---

test/MuxManagerTest.cpp

Summary:
Unable to cherry-pick these commits from master: 
4bf8b3d  wait for handler to be completed (#114)
d4540ba Adjust `DbInterfaceRaceConditionCheck` to Wait Longer for Handlers to be executed (#111)
Submitting PR to pick up manually. 
sign-off: Jing Zhang zhangjinng@microsoft.com

[202012] Cherry-pick flaky unit test fixes 

---

azure-pipelines.yml

Summary:
Fix Azure pipeline.
```
Unpacking libswsscommon (1.0.0) ...
dpkg: dependency problems prevent configuration of libswsscommon:
libswsscommon depends on libboost-serialization1.71.0; however:
Package libboost-serialization1.71.0 is not installed.
```
1. Add `libboost-serialization` to the package list.
2. Use a specific `swss-common` build as the last version has some dependency conflicts.

Fix azure pipeline

---

azure-pipelines.yml

Summary:
To cherry-pick PR #118 into `202205`.

[202205] Fix pipeline 

---

src/DbInterface.cpp
src/DbInterface.h

Summary:
To cherry-pick #108 into `202205` branch.

[202205] Fix peer toggle

---

azure-pipelines.yml
lgtm.yml
src/DbInterface.cpp
src/DbInterface.h
src/MuxPort.h
src/link_manager/LinkManagerStateMachine.cpp
src/link_manager/LinkManagerStateMachine.h
test/FakeDbInterface.cpp
test/FakeDbInterface.h
test/FakeLinkProber.cpp
test/FakeLinkProber.h
test/LinkManagerStateMachineTest.cpp

Summary:
Cherry-pick conflict: 
ea68e8c Jing Zhang      Wed Sep 21 10:52:18 2022 -0700  Post switchover reasons to STATE DB (#131)
a5a9f90 Hua Liu Fri Sep 16 09:54:32 2022 +0800  Install libyang to azure pipeline (#132)

[202012][Cherry-pick] Post switchover reasons to STATE DB

---

src/DbInterface.cpp
src/MuxManager.h
src/common/MuxConfig.h
src/common/MuxPortConfig.h
src/link_prober/LinkProber.cpp
test/MuxManagerTest.cpp
test/MuxManagerTest.h

Summary:
Cherry-pick https://github.com/sonic-net/sonic-linkmgrd/pull/152 into `202012` branch.

[202012] update link prober stats updating frequency to 30s 

---

src/link_prober/LinkProber.cpp
src/link_prober/LinkProberStateMachineActiveActive.cpp
test/FakeLinkProber.cpp

Fix the warning of unused variables

---

azure-pipelines.yml

Summary:
run 'apt-get update' before 'apt-get install'

[ci] Fix apt-get install unable locate package issue.

---

azure-pipelines.yml

Summary:
Cherry-pick conflict: 
079ae1a Liu Shilong     Tue Feb 28 19:47:32 2023 +0800  [ci] Fix apt-get install unable locate package issue. (#177)

[202012][ci] Fix apt-get install unable locate package issue. (#177)

---

src/MuxPort.cpp
src/link_manager/LinkManagerStateMachineActiveActive.cpp

Summary:
As the subject, add some logs and increase verbosity for mux config and default route handlers to help debug.

Increase verbosity for mux config and default route handlers 

---

azure-pipelines.yml

Summary:
swss-common pipeline is now based on Bullseye.
Also, switch armhf and arm64 to Bullseye

Update swss-common pipeline artifact name

---

azure-pipelines.yml

Summary:
[ci] remove hard coded source branch name in azp file

[ci] remove hard coded source branch name in azp file

---

azure-pipelines.yml

Summary:
08fc401 (HEAD -> 202205, origin/202205) [ci] remove hard coded source branch name in azp file  (#198)
093cb36 Update swss-common pipeline artifact name (#195)

[202205] cherry-pick `azure-pipeline.yml` updates

---

.github/workflows/codeql-analysis.yml

Summary:
1. use `pull_request` as trigger to include PR changes in analysis.
* **NOTE**: `pull_request_target` doesn't include PR changes in the analysis, it is pointless to do so in PR testing.
3. ensure link directory(`-L`) is added before relative library(`-l`) in
linking.
As the motivation

[codeql] Fix codeql issues 

---

.github/workflows/codeql-analysis.yml

Summary:
9fba1c9 Longxiang Lyu   Wed Apr 26 00:53:16 2023 +0800  [codeql] Fix codeql issues  (#205)
d464b1f Jing Zhang      Mon Apr 24 21:15:18 2023 -0700  [codeql] remove hard coded line numbers in sed commands (#203)

[202012] pick codeql fixes

---

src/link_manager/LinkManagerStateMachine.cpp
src/link_manager/LinkManagerStateMachine.h
test/FakeMuxPort.h
test/LinkManagerStateMachineTest.cpp

[202012][active-standby][bsl] fix no mux probe issue #201

---

azure-pipelines.yml

Change common_libs dependencies from buster to bullseye

---

.github/pull_request_template.md

Add ADO tracking to the PR template

---

.github/workflows/codeql-analysis.yml

Summary:
Fix unmet build dependencies. 

[CodeQL] fix unmet build dependency

---

.github/workflows/codeql-analysis.yml

[CodeQL] Use correct sonic-swss-common package.

---

src/DbInterface.cpp

Summary:
Raising log level to `notice` for timed oscillation config change.
28557265

[active-standby] raising log level to `notice` for timed oscillation config change

---

azure-pipelines.yml

Summary:
swss-common has vstest issues.
Don't block linkmgrd by swss common vstest.
Pipeline change
- Microsoft ADO **(number only)**:  29246135

Fix pipeline for 202305 swss common vstest failed.

---

test/LinkManagerStateMachineTest.cpp

Summary:
Cherry-pick https://github.com/sonic-net/sonic-linkmgrd/pull/258 into 202305.

Fix default route race condition UT

---

azure-pipelines.yml

Summary:
Migrate the pipeline to use bookworm.
- Microsoft ADO **(number only)**: 31366434

Fix pipeline to use bookwarm

---

.github/workflows/codeql-analysis.yml
azure-pipelines.yml

Summary:
[ci][build] deprecate ubuntu 20.04 agent pool

[ci][build] deprecate ubuntu 20.04 agent pool
